// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// ============================================================
//  Groth16Verifier
//  Auto-generated by snarkJS from AgeVerify.circom
//  DO NOT edit the constants below.
// ============================================================
contract Groth16Verifier {
    uint256 constant r  = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 constant q  = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 constant alphax  = 90481012016520068451691005522755697964918949206348922079438302173735489606;
    uint256 constant alphay  = 5640115478002837118123195565994184597623886131539989876275318954034439600203;
    uint256 constant betax1  = 10719388885903693610234847173145564580631633535572628549833984094522836926175;
    uint256 constant betax2  = 21340922833911509000458657859289670219605307389317668663872486178947544838822;
    uint256 constant betay1  = 21025873816870852173326464775821318621840436632839007744452339303446183051529;
    uint256 constant betay2  = 6919370548321236567068048307234356458923062951363519000313890173594513161933;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 8692726083801219831743332277473644355711632115509569180990211899672203197976;
    uint256 constant deltax2 = 4202157286233144647761362215316437206720708051906515928455886716125066913574;
    uint256 constant deltay1 = 15919915968463848619483282059507220080277494864562264885358179105497028805430;
    uint256 constant deltay2 = 5548456516111951762800555320438198766603253924228679106228944573005097266864;

    uint256 constant IC0x = 3757465988184372130578077230852215333694182722655985973395858442586633068462;
    uint256 constant IC0y = 5350990694779832076867797471536372560414331130470004826104394817918247750263;
    uint256 constant IC1x = 9710507574502653201119146187835292014789373639199695866858581997975108022874;
    uint256 constant IC1y = 1810743202108262832297523621853172120088091008481713725054231373593747144107;
    uint256 constant IC2x = 12311534079288900262213856957268753860045475028154590795663710176147171290323;
    uint256 constant IC2y = 15391330719081620742609334433558612716146030826009857231113080145788376500432;
    uint256 constant IC3x = 6283389423673037316359558763014110308859656941588460021534631151218480197260;
    uint256 constant IC3y = 4846129538164515950370320486469148984202159275313067575208815562610641281685;

    uint16 constant pVk      = 0;
    uint16 constant pPairing = 128;
    uint16 constant pLastMem = 896;

    function verifyProof(
        uint[2]    calldata _pA,
        uint[2][2] calldata _pB,
        uint[2]    calldata _pC,
        uint[3]    calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)
                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) { mstore(0, 0) return(0, 0x20) }
                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))
                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) { mstore(0, 0) return(0, 0x20) }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk      := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))

                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))
                mstore(add(_pPairing, 64),  calldataload(pB))
                mstore(add(_pPairing, 96),  calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)
                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)
            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}

// ============================================================
//  AgeVerifier
//  Deploy THIS contract only — it creates Groth16Verifier
//  internally. No constructor arguments needed.
// ============================================================
contract AgeVerifyExtension {

    Groth16Verifier public immutable verifier;

    mapping(address => bool)    public isAdultVerified;
    mapping(address => uint256) public verifiedAt;

    event AgeVerified(address indexed user, uint256 timestamp);

    /// @dev Deploys and owns its own Groth16Verifier instance.
    constructor() {
        verifier = new Groth16Verifier();
    }

    /**
     * @dev Submit a ZK proof to verify age >= 18.
     * @param a      Groth16 proof A  [2]
     * @param b      Groth16 proof B  [2][2]
     * @param c      Groth16 proof C  [2]
     * @param input  Public signals: [isAdult=1, currentYear, minAge=18]
     */
    function submitAgeProof(
        uint[2]    calldata a,
        uint[2][2] calldata b,
        uint[2]    calldata c,
        uint[3]    calldata input
    ) external {
        require(input[0] == 1,  "Proof: isAdult must be 1");
        require(input[2] == 18, "Proof: minAge must be 18");
        require(input[1] >= 2020 && input[1] <= 2100, "Proof: invalid currentYear");

        require(verifier.verifyProof(a, b, c, input), "Invalid ZK proof");

        isAdultVerified[msg.sender] = true;
        verifiedAt[msg.sender]      = block.timestamp;

        emit AgeVerified(msg.sender, block.timestamp);
    }

    function checkAdultStatus(address user) external view returns (bool) {
        return isAdultVerified[user];
    }

    function getVerificationDetails(address user)
        external view
        returns (bool verified, uint256 timestamp)
    {
        return (isAdultVerified[user], verifiedAt[user]);
    }
}
