/**
 * Generates a self-contained circomlibjs_poseidon.js for use in Android WebView.
 * Only extracts the t=4 (3-input) Poseidon constants for BN128.
 * Run: node scripts/generate_poseidon_browser.js
 */

const { buildPoseidon } = require('../node_modules/circomlibjs/build/main.cjs');
const path = require('path');
const fs   = require('fs');

const OUT = path.join(__dirname,
    '../../BlockchainHealthWallet/app/src/main/assets/zkp/circomlibjs.min.js');

async function main() {
    const poseidon = await buildPoseidon();
    const F = poseidon.F;
    const p = F.p.toString();

    // Verify the field prime is BN128
    const BN128_P = '21888242871839275222246405745257275088548364400416034343698204186575808495617';
    if (p !== BN128_P) throw new Error('Unexpected field prime: ' + p);

    // Generate the test vector so we can embed a self-test
    const r1 = poseidon([1n, 1n, 12345n]);
    const testVector = F.toString(r1);

    // -----------------------------------------------------------------
    // Extract constants for t=4 (3 inputs) from the built instance
    // by calling poseidon once and recording intermediate state.
    // -----------------------------------------------------------------
    // Instead of trying to read private fields, we generate the constants
    // by running the Reference implementation which exposes them.
    const { buildPoseidonReference } = require('../node_modules/circomlibjs/build/main.cjs');
    const posRef = await buildPoseidonReference();

    // Read the raw constants from poseidon_constants_opt.js for t=4 (index 2)
    const rawConstants = require('../node_modules/circomlibjs/src/poseidon_constants_opt.js');
    const C4 = rawConstants.default.C[2]; // t=4 → index 2
    const M4 = rawConstants.default.M[2];
    const P4 = rawConstants.default.P[2];
    const S4 = rawConstants.default.S[2];

    console.log(`C4 length: ${C4.length}`);
    console.log(`M4: ${M4.length}x${M4[0].length}`);
    console.log(`P4: ${P4.length}x${P4[0].length}`);
    console.log(`S4 length: ${S4.length}`);

    // Correct nRoundsP for t=4: index 2 from N_ROUNDS_P array
    const N_ROUNDS_P_T4 = 56;  // index 2 of [56,57,56,60,...] for t=4

    // Verify
    const expectedSLen = N_ROUNDS_P_T4 * (2 * 4 - 1); // 56 * 7 = 392
    if (S4.length !== expectedSLen) {
        throw new Error(`S4 length mismatch: ${S4.length} vs ${expectedSLen}`);
    }

    // -----------------------------------------------------------------
    // Write the browser-compatible JS
    // -----------------------------------------------------------------
    const js = `/**
 * circomlibjs Poseidon (t=4, BN128) — browser compatible
 * Auto-generated by scripts/generate_poseidon_browser.js
 * Constants from circomlibjs (iden3/circomlibjs)
 *
 * Exposes: buildPoseidon() -> Promise<poseidonFn>
 * poseidonFn([a, b, c]) -> BigInt   (for 3-input Poseidon)
 * poseidonFn.F.toString(result) -> decimal string
 */
(function(global) {
    'use strict';

    const FIELD_P = BigInt("${BN128_P}");

    function mod(a) {
        const r = a % FIELD_P;
        return r < 0n ? r + FIELD_P : r;
    }
    function addF(a, b) { return mod(a + b); }
    function mulF(a, b) { return mod(a * b); }
    function pow5(a) {
        const a2 = mulF(a, a);
        const a4 = mulF(a2, a2);
        return mulF(a4, a);
    }
    function fromStr(s) {
        return /^0x/i.test(s) ? BigInt(s) : BigInt(s);
    }

    const N_ROUNDS_F  = 8;
    const N_ROUNDS_P4 = ${N_ROUNDS_P_T4}; // for t=4

    // Round constants C
    const C_raw = ${JSON.stringify(C4)};
    // MDS matrix M (full rounds)
    const M_raw = ${JSON.stringify(M4)};
    // Pre-image partial constants Pc (transition round)
    const Pc_raw = ${JSON.stringify(P4)};
    // Sparse MDS S (partial rounds)
    const S_raw = ${JSON.stringify(S4)};

    const C  = C_raw.map(fromStr);
    const M  = M_raw.map(row => row.map(fromStr));
    const Pc = Pc_raw.map(row => row.map(fromStr));
    const S  = S_raw.map(fromStr);

    // Optimized Poseidon matching circomlibjs buildPoseidon (= buildPoseidonOpt)
    function poseidon(inputs) {
        if (inputs.length !== 3) throw new Error('This bundle only supports 3 inputs');
        const t = 4;
        const nRoundsF = N_ROUNDS_F;
        const nRoundsP = N_ROUNDS_P4;

        let state = [0n, ...inputs.map(a => mod(typeof a === 'bigint' ? a : BigInt(a.toString())))];

        // Initial round constant addition
        state = state.map((a, i) => addF(a, C[i]));

        // First half full rounds (nRoundsF/2 - 1 = 3 rounds)
        for (let r = 0; r < nRoundsF / 2 - 1; r++) {
            state = state.map(a => pow5(a));
            state = state.map((a, i) => addF(a, C[(r + 1) * t + i]));
            const snap = state.slice();
            state = state.map((_, i) =>
                snap.reduce((acc, a, j) => addF(acc, mulF(M[j][i], a)), 0n)
            );
        }
        // Last full round of first half — uses Pc (partial-transition matrix)
        state = state.map(a => pow5(a));
        state = state.map((a, i) => addF(a, C[(nRoundsF / 2) * t + i]));
        {
            const snap = state.slice();
            state = state.map((_, i) =>
                snap.reduce((acc, a, j) => addF(acc, mulF(Pc[j][i], a)), 0n)
            );
        }

        // Partial rounds (only state[0] goes through S-box)
        for (let r = 0; r < nRoundsP; r++) {
            state[0] = pow5(state[0]);
            state[0] = addF(state[0], C[(nRoundsF / 2 + 1) * t + r]);
            const s0 = state.reduce((acc, a, j) => addF(acc, mulF(S[(t * 2 - 1) * r + j], a)), 0n);
            for (let k = 1; k < t; k++) {
                state[k] = addF(state[k], mulF(S[(t * 2 - 1) * r + t + k - 1], state[0]));
            }
            state[0] = s0;
        }

        // Second half full rounds (nRoundsF/2 - 1 = 3 rounds)
        for (let r = 0; r < nRoundsF / 2 - 1; r++) {
            state = state.map(a => pow5(a));
            state = state.map((a, i) =>
                addF(a, C[(nRoundsF / 2 + 1) * t + nRoundsP + r * t + i])
            );
            const snap = state.slice();
            state = state.map((_, i) =>
                snap.reduce((acc, a, j) => addF(acc, mulF(M[j][i], a)), 0n)
            );
        }
        // Final full round — no round constants, just S-box + MDS
        state = state.map(a => pow5(a));
        {
            const snap = state.slice();
            state = state.map((_, i) =>
                snap.reduce((acc, a, j) => addF(acc, mulF(M[j][i], a)), 0n)
            );
        }

        return state[0]; // capacity element is the output
    }

    poseidon.F = {
        p: FIELD_P,
        e: a => mod(typeof a === 'bigint' ? a : BigInt(a.toString())),
        toString: a => a.toString(),
        toObject: a => a
    };

    // Self-test on load
    const _tv = poseidon([1n, 1n, 12345n]).toString();
    const _expected = "${testVector}";
    if (_tv !== _expected) {
        throw new Error('Poseidon self-test FAILED. Got ' + _tv + ' expected ' + _expected);
    }

    async function buildPoseidon() {
        return poseidon;
    }

    // Export: CommonJS + browser global
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = { buildPoseidon, poseidon };
    } else {
        global.buildPoseidon = buildPoseidon;
        global.circomlibjs   = { buildPoseidon, poseidon };
    }

})(typeof globalThis !== 'undefined' ? globalThis : typeof window !== 'undefined' ? window : this);
`;

    fs.writeFileSync(OUT, js, 'utf8');
    console.log(`Written: ${OUT}  (${Math.round(js.length / 1024)}KB)`);
    console.log(`Test vector (1,1,12345): ${testVector}`);
}

main().catch(err => { console.error(err); process.exit(1); });
